# Generated by Django 5.0 on 2024-01-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='accout_type',
            new_name='account_type',
        ),
    ]
