# Generated by Django 5.0 on 2024-01-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transfer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Loan'), (4, 'Loan Paid')], null=True),
        ),
    ]
